FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_claims_app.py .
COPY insurance_bg.jpg .

CMD ["streamlit", "run", "streamlit_claims_app.py", "--server.port=8501", "--server.address=0.0.0.0"]